allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  bcrypt: set this to true or false
  prisma: true
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - supertest@7.3.1
